// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run through the session pooler (DDL-safe), not the
    // transaction pooler the app uses at runtime for regular queries.
    url: process.env["DIRECT_URL"],
  },
});
